const AppActionTypes = {
   SELECT_DATE: 'SELECT_DATE',
   SWIPE_DATE_PICKER: 'SWIPE_DATE_PICKER',
   CHANGE_MEAL_TIME: 'CHANGE_MEAL_TIME',
   ADD_TO_CART: 'ADD_TO_CART',
   FILTER_MEALS: 'FILTER_MEALS',
   GET_TOTAL_PRICE: 'GET_TOTAL_PRICE',
   TOGGLE_HIDDEN_LOCATION_MODAL : 'TOGGLE_HIDDEN_LOCATION_MODAL'
} 

export default AppActionTypes;